=== IGNF/geopf-extensions-openlayers/src/packages/Utils/schemas/territories.schema.json
{
  "$id": "territories",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "title", "description", "zoom", "thumbnail", "icon"],
    "oneOf": [
        { "required": ["bbox"] },
        { "required": ["point"] }
    ],
    "properties": {
      "id": {
        "type": "string",
        "description": "Code du territoire"
      },
      "title": {
        "type": "string",
        "description": "Nom affiché du territoire"
      },
      "description": {
        "type": "string"
      },
      "zoom": {
        "type": ["integer", "null"],
        "minimum": 0
      },
      "bbox": {
        "type": "array",
        "minItems": 4,
        "maxItems": 4,
        "items": {
          "type": "number"
        },
        "description": "Bounding box au format [minX, minY, maxX, maxY]"
      },
      "point": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": { "type": "number" },
        "description": "Coordonnées"
      },
      "thumbnail": {
        "type": "string",
        "format": "uri"
      },
      "icon": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== IGNF/geopf-extensions-openlayers/samples-src/resources/data/territories-custom.json
[
    {
        "id": "SSM",
        "title": "Services Saint-Mandé",
        "description": "Services Saint-Mandé",
        "zoom": 16,
        "point": [2.424444253967285,48.84563414811194],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTCE",
        "title": "DT centre-est",
        "description": "Direction territoriale centre-est",
        "zoom": 16,
        "point": [4.853185169311518,45.754797579836975],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTGON",
        "title": "DT site de Nantes",
        "description": "Direction territoriale grand-ouest (site de Nantes)",
        "zoom": 16,
        "point": [-1.5430467460327155,47.20651117967003],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTGOC",
        "title": "DT site de Caen",
        "description": "Direction territoriale grand-ouest (site de Caen",
        "zoom": 16,
        "point": [-0.3491729999999998,49.19963967566363],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTSE",
        "title": "DT sud-est",
        "description": "",
        "zoom": 16,
        "point": [5.370966501371475,43.478702489381675],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTNN",
        "title": "DT nord",
        "description": "Direction territoriale nord et outre-mer (site de Champigneulles)",
        "zoom": 16,
        "point": [6.1562635423278795,48.73997763280997],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "DTSO",
        "title": "DT sud-ouest",
        "description": "Direction territoriale sud-ouest",
        "zoom": 16,
        "point": [-0.7423062883605956,44.89091269402681],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "SIS",
        "title": "Service de l'imagerie spatiale",
        "description": "Service de l'imagerie spatiale",
        "zoom": 16,
        "point": [1.481507457672119,43.561871100286226],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "SIA",
        "title": "Service de l'imagerie et de l'aéronautique",
        "description": "Service de l'imagerie et de l'aéronautiqu",
        "zoom": 16,
        "point": [2.106011373016357,49.45413126936026],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "SISFE",
        "title": "Service de l'information forestière",
        "description": "Service de l'information statistique forestière et environnementale",
        "zoom": 16,
        "point": [2.761920711639404,47.835724827317165],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "ENSG",
        "title": "ENSG-Géomatique",
        "description": "ENSG-Géomatique",
        "zoom": 16,
        "point": [2.588662626983642,48.84047113864244],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    },
    {
        "id": "SLOG",
        "title": "Site logistique et patrimonial",
        "description": "Site logistique et patrimonial",
        "zoom": 16,
        "point": [1.7139914576721194,47.29548159183565],
        "thumbnail": "",
        "icon": "/samples/resources/data/IGN.png"
    }
]

=== IGNF/geopf-extensions-openlayers/src/packages/Controls/Territories/Territories.json
[
    {
        "id": "FXX",
        "title": "France métropolitaine",
        "description": "",
        "zoom": null,
        "bbox": [-9.86, 41.15, 10.38, 51.56],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/fxx.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/fxx.svg"
    },
    {
        "id": "GLP",
        "title": "Guadeloupe",
        "description": "",
        "zoom": null,
        "bbox": [ -61.97, 15.72, -60.93, 16.66],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/glp.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/glp.svg"
    },
    {
        "id": "GUF",
        "title": "Guyane",
        "description": "",
        "zoom": null,
        "bbox": [-55.65, 1.49, -51.20, 6.21],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/guf.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/guf.svg"
    },
    {
        "id": "MTQ",
        "title": "Martinique",
        "description": "",
        "zoom": null,
        "bbox": [-61.40, 14.25, -60.67, 15.04],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/mtq.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/mtq.svg"
    },
    {
        "id": "REU",
        "title": "Réunion",
        "description": "",
        "zoom": 10,
        "bbox": [55.07, -21.46, 55.86, -20.79],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/reu.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/reu.svg"
    },
    {
        "id": "SPM",
        "title": "Saint-Pierre-et-Miquelon",
        "description": "",
        "zoom": null,
        "bbox": [-56.48, 46.69, -56.07, 47.19],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/spm.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/spm.svg"
    },
    {
        "id": "IDF",
        "title": "Paris petite couronne",
        "description": "",
        "zoom": 12,
        "bbox": [2.18, 48.77, 2.52, 48.95],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/idf.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/idf.svg"
    },
    {
        "id": "MYT",
        "title": "Mayotte",
        "description": "",
        "zoom": null,
        "bbox": [44.95, -13.049, 45.32, -12.57],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/myt.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/myt.svg"
    },
    {
        "id": "NCL",
        "title": "Nouvelle Calédonie",
        "description": "",
        "zoom": null,
        "bbox": [163.02,-23.08, 167.86,-19.50],
        "thumbnail": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/thumbnails/ncl.png",
        "icon": "https://data.geopf.fr/annexes/cartes.gouv.fr-config/public/resources/territories/ncl.svg"
    }
]
